spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarydb
    username: root
    password: Arjun@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretkey: "your-256-bit-secret-your-256-bit-secret-1234" # Must be at least 32 chars
  expiration: 3600000 # 1 hour in milliseconds
